#!/bin/bash
#
# [y] hybris Platform
#
# Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved.
#
# This software is the confidential and proprietary information of SAP
# ("Confidential Information"). You shall not disclose such Confidential
# Information and shall use it only in accordance with the terms of the
# license agreement you entered into with SAP.
#

# Identify OS
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)
      OS=Linux
      ;;
    Darwin*)
      OS=Mac
      ;;
    CYGWIN*)
      OS=Cygwin
      ;;
    MINGW*)
      OS=MinGw
      ;;
    *)
      OS="UNKNOWN:${unameOut}"
esac

# Set KITBAG_HOME variable
if [ -z ${KITBAG_HOME} ]; then
  KITBAG_HOME=$(cd "$(dirname $0)" && pwd)
fi

# Set KITBAG_DEBUG variable
if [[ "${KITBAG_DEBUG}" =~ ^(yes|1|true)$ ]]; then
  KITBAG_DEBUG=1
else
  KITBAG_DEBUG=0
fi

# Load global functions
source ${KITBAG_HOME}/lib/utils.sh
source ${KITBAG_HOME}/lib/core.sh

# Start dispatching
parseArgs "${@}"
loadConfigFile
dispatch
