#!/bin/bash

# Identify OS
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)
      OS=Linux
      ;;
    Darwin*)
      OS=Mac
      ;;
    CYGWIN*)
      OS=Cygwin
      ;;
    MINGW*)
      OS=MinGw
      ;;
    *)
      OS="UNKNOWN:${unameOut}"
esac

# Set KITBAG_HOME variable
if [ -z ${KITBAG_HOME} ]; then
  KITBAG_HOME=$(cd "$(dirname $0)" && pwd)
fi

# Set KITBAG_DEBUG variable
if [[ "${KITBAG_DEBUG}" =~ ^(yes|1|true)$ ]]; then
  KITBAG_DEBUG=1
else
  KITBAG_DEBUG=0
fi

# Load global functions
source ${KITBAG_HOME}/lib/utils.sh
source ${KITBAG_HOME}/lib/core.sh

# Start dispatching
parseArgs "${@}"
loadConfigFile
dispatch
